version: "3.8"
 
services:
  backend:
    build:
      context: ./back-end-redbus
      dockerfile: Dockerfile
    container_name: redbus-backend
    ports:
      - "5000:5000"
    env_file:
      - ./back-end-redbus/config.env
    restart: always
 
  frontend:
    build:
      context: ./front-end-redbus
      dockerfile: Dockerfile
    container_name: redbus-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: always
